import React, { useMemo, useState } from 'react';
import { BookOpen, CalendarClock, CheckCircle2, RotateCcw, Search, ShieldAlert, Wrench } from 'lucide-react';

const Step = ({ no, title, children }: { no: number; title: string; children: React.ReactNode }) => <div className="flex gap-3 rounded-xl border bg-white p-3 sm:p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-indigo-600 text-sm font-black text-white">{no}</span><div><h4 className="font-bold text-slate-800">{title}</h4><div className="mt-1 text-sm leading-6 text-slate-600">{children}</div></div></div>;
const Note = ({ children, warning = false }: { children: React.ReactNode; warning?: boolean }) => <div className={`rounded-xl border p-3 text-sm leading-6 ${warning ? 'border-amber-300 bg-amber-50 text-amber-900' : 'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>;

const ServiceHelpPage: React.FC = () => {
  const [search, setSearch] = useState('');
  const sections = [
    { id: 'workflow', title: 'လုပ်ငန်းစဉ်အကျဉ်း', keywords: 'workflow booking service settlement closed rework', icon: <BookOpen />, body: <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{['ပစ္စည်းလက်ခံ', 'Service Job ပြောင်း', 'စစ်ဆေး/ပြင်ဆင်', 'ငွေရှင်း/ပေးအပ်', 'လိုအပ်လျှင် Rework'].map((v, i) => <div key={v} className="rounded-xl border p-4 text-center"><div className="text-xs font-black text-indigo-500">STEP {i + 1}</div><b className="mt-1 block text-sm">{v}</b></div>)}</div><Note>Booking သည် ပစ္စည်းလက်ခံမှတ်တမ်းဖြစ်သည်။ Part၊ Stock၊ Payment နှင့် Rework အားလုံးကို Service Job မှဆောင်ရွက်ပါ။</Note></> },
    { id: 'booking', title: 'ပစ္စည်းလက်ခံ (Booking)', keywords: 'booking customer device serial accessories shelf convert', icon: <CalendarClock />, body: <><div className="space-y-2"><Step no={1} title="ဖောက်သည်ရွေးပါ">အမည်/ဖုန်းဖြင့်ရှာပါ။ မရှိလျှင် အသစ်ထည့်ပါ။</Step><Step no={2} title="ပစ္စည်းအချက်အလက်ဖြည့်ပါ">Brand၊ Model၊ Serial၊ Color၊ Accessories၊ Condition၊ Problem နှင့် Shelf ကိုမှတ်တမ်းတင်ပါ။</Step><Step no={3} title="Review နှင့် Save">ဖောက်သည်ရှေ့တွင် Serial၊ Accessories နှင့် ချို့ယွင်းချက်ကိုအတည်ပြုပါ။</Step><Step no={4} title="Service Job ပြောင်းပါ">Technician လက်ခံချိန်တွင် တစ်ကြိမ်သာပြောင်းပါ။</Step></div><Note warning>Booking မှ Rework မဖန်တီးရပါ။ မူလ Closed Service Job မှသာဖန်တီးပါ။</Note></> },
    { id: 'service', title: 'ဝန်ဆောင်မှုလုပ်ငန်း', keywords: 'service technician diagnosis part settlement closed', icon: <Wrench />, body: <div className="space-y-2"><Step no={1} title="Job ကိုလက်ခံပါ">Technician နှင့် Shelf သတ်မှတ်ပါ။</Step><Step no={2} title="Diagnosis မှတ်တမ်းတင်ပါ">Service၊ Part၊ Qty၊ Serial နှင့် Estimate ထည့်ပါ။</Step><Step no={3} title="Status ပြောင်းပါ">လက်ခံပြီး → စစ်ဆေးဆဲ → လုပ်ဆောင်ဆဲ → ပြီးစီး။</Step><Step no={4} title="ငွေရှင်းပါ">Final Cost၊ Discount၊ Payment သို့မဟုတ် အကြွေးကိုအတည်ပြုပြီး Settlement လုပ်ပါ။</Step><Step no={5} title="ပစ္စည်းပေးအပ်ပါ">အမှန်တကယ်ပေးပြီးမှ Closed လုပ်ပါ။</Step></div> },
    { id: 'tabs', title: 'ရှာဖွေခြင်းနှင့် Tabs', keywords: 'active all credit history today', icon: <Search />, body: <div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border bg-blue-50 p-4"><b>လုပ်ဆောင်ဆဲ</b><p className="mt-2 text-sm">ရက်မကန့်သတ်ဘဲ မပြီးသေးသော Job များပြသည်။</p></div><div className="rounded-xl border bg-slate-50 p-4"><b>အားလုံး</b><p className="mt-2 text-sm">Default ယနေ့ data။ ရှာဖွေလျှင် history အားလုံးရှာသည်။</p></div><div className="rounded-xl border bg-rose-50 p-4"><b>အကြွေးကျန်</b><p className="mt-2 text-sm">Due Amount ကျန်သည့် Job များပြသည်။</p></div></div> },
    { id: 'rework', title: 'Warranty / Rework', keywords: 'warranty replace upgrade refund quarantine serial', icon: <RotateCcw />, body: <><Note>Closed Job ကို “အားလုံး” tab မှရှာပြီး Rework ခလုတ်နှိပ်ပါ။</Note><div className="grid gap-3 sm:grid-cols-2">{[['Service သာ','Part မလဲဘဲပြန်ပြင်'],['အစားထိုး','မူလ Part credit အတွင်းလဲပေး'],['Upgrade','စျေးနှုန်းကွာဟချက်ကောက်ခံ'],['Refund','Credit မကျော်သောငွေပြန်အမ်း']].map(([a,b]) => <div key={a} className="rounded-xl border p-4"><b>{a}</b><p className="mt-1 text-sm text-slate-600">{b}</p></div>)}</div><p className="text-sm leading-7"><b>ပစ္စည်းဟောင်း:</b> Quarantine၊ Damaged၊ Supplier Return သို့မဟုတ် Reuse ရွေးပါ။</p><p className="text-sm leading-7"><b>Serial:</b> Product ရွေးပြီး Available Serial များထဲမှ Qty အတိုင်း checkbox ဖြင့်ရွေးပါ။</p></> },
    { id: 'rules', title: 'နေ့စဉ် Checklist', keywords: 'checklist rules', icon: <ShieldAlert />, body: <div className="grid gap-2 sm:grid-cols-2">{['Customer၊ ဖုန်းနှင့် ပစ္စည်းစစ်ပါ', 'Serial နှင့် Accessories အတည်ပြုပါ', 'Booking ကို Job နှစ်ခါမပြောင်းပါနှင့်', 'Part Qty/Serial ကို Settlement မတိုင်မီစစ်ပါ', 'ပစ္စည်းမပေးရသေးဘဲ Closed မလုပ်ပါနှင့်', 'Rework ကို Closed Job မှသာလုပ်ပါ', 'Refund/Upgrade ကို Manager အတည်ပြုပါ', 'နေ့ကုန်တွင် လုပ်ဆောင်ဆဲ/အကြွေးကျန်စစ်ပါ'].map(v => <div key={v} className="flex gap-2 rounded-xl border p-3 text-sm"><CheckCircle2 className="shrink-0 text-emerald-600" size={18}/>{v}</div>)}</div> },
  ];
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return q ? sections.filter(s => `${s.title} ${s.keywords}`.toLowerCase().includes(q)) : sections; }, [search]);
  return <div className="mx-auto max-w-6xl space-y-5 pb-12"><section className="rounded-2xl bg-gradient-to-br from-indigo-700 to-purple-700 p-5 text-white shadow-lg sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-200">User Manual & SOP</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Booking နှင့် ဝန်ဆောင်မှုလုပ်ငန်း လမ်းညွှန်</h1><p className="mt-2 text-sm text-indigo-100">ပစ္စည်းလက်ခံမှ Warranty/Rework အထိ ဝန်ထမ်းအသုံးပြုနည်း။</p><div className="relative mt-5 max-w-xl"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Booking၊ Serial၊ Refund... ရှာပါ" className="w-full rounded-xl py-3 pl-10 pr-4 text-base text-slate-800"/></div></section><nav className="flex gap-2 overflow-x-auto">{sections.map(s => <a key={s.id} href={`#${s.id}`} className="whitespace-nowrap rounded-full border bg-white px-3 py-1.5 text-xs font-bold">{s.title}</a>)}</nav>{filtered.map(s => <section id={s.id} key={s.id} className="rounded-2xl border bg-white shadow-sm"><header className="flex items-center gap-3 border-b p-4 sm:px-6"><span className="text-indigo-600">{s.icon}</span><h2 className="text-lg font-black sm:text-xl">{s.title}</h2></header><div className="space-y-4 p-4 sm:p-6">{s.body}</div></section>)}</div>;
};
export default ServiceHelpPage;