package org.sspd.servicemgmt.servicejoboptions.dto;

import lombok.Data;
import org.sspd.servicemgmt.servicejoboptions.model.ReworkType;
import org.sspd.servicemgmt.servicejoboptions.model.ReworkResolutionMode;
import org.sspd.servicemgmt.servicejoboptions.model.OldPartDisposition;
import org.sspd.servicemgmt.servicejoboptions.model.ServiceJobStatus;
import org.sspd.servicemgmt.servicejoboptions.model.ServiceMode;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Data
public class ServiceJobDTO {
    private Integer id;
    private String jobNo;
    private Integer customerId;
    private String customerName;
    private ServiceMode serviceMode;
    private BigDecimal customerLatitude;
    private BigDecimal customerLongitude;
    private Integer assignedStaffId;
    private String assignedStaffName;
    private String itemName;
    private String deviceType;
    private String itemCondition;
    private String deviceConditions;
    private String partRequests;
    private String problemDesc;
    private String diagnosisNotes;
    private BigDecimal estimatedCost;
    private BigDecimal finalCost;
    private BigDecimal discountAmount;
    private Boolean foc;
    private BigDecimal netAmount;
    private BigDecimal paidAmount;
    private BigDecimal dueAmount;
    private LocalDate dueDate;
    private String paymentStatus;
    private String creditStatus;
    private String receivedDate;
    private String estimatedCompletion;
    private String completedDate;
    private String deliveredDate;
    private ServiceJobStatus status;
    private Integer paymentMethodId;
    private String paymentMethodName;
    private Integer bookingId;
    private String bookingNo;
    private Integer saleId;
    private String customerPhone;
    private String color;
    private String serialNo;
    private String accessories;
    private Integer shelfLocationId;
    private String shelfLocationCode;
    private String shelfLocationLabel;
    private boolean rework;
    private Integer parentJobId;
    private String parentJobNo;
    private ReworkType reworkType;
    private String replacementItemName;
    private String replacementSerialNo;
    private String replacementReason;
    private ReworkResolutionMode resolutionMode;
    private OldPartDisposition oldPartDisposition;
    private String originalPartName;
    private String originalPartCode;
    private List<String> originalPartSerialNumbers;
    private String replacementProductName;
    private String replacementProductCode;
    private List<String> replacementPartSerialNumbers;
    private Integer replacementQty;
    private BigDecimal warrantyCredit;
    private BigDecimal replacementPrice;
    private BigDecimal customerCharge;
    private BigDecimal refundAmount;
    private String refundPaymentMethodName;
    private String refundTransactionNo;
    private String refundDate;
    private String remark;
    private Boolean voided;
    private String voidReason;
    private String voidedBy;
    private String voidedAt;
    private Boolean estimateApproved;
    private String estimateApprovedAt;
    private String estimateApprovedBy;
    private String priority;
    private Integer helperStaffId;
    private String helperStaffName;
    private String holdReason;
    private String workStartedAt;
    private String lastNotifiedAt;
    private String modifiedBy;
    private String modifiedAt;
    private Long technicianMinutes;
    private Boolean overdue;
    private List<ServiceJobLineDTO> lines;
    private List<ServiceJobPartDTO> productParts;
    private List<ServiceJobActivityDTO> activities;
    private List<ServiceJobAttachmentDTO> attachments;
    private List<ServiceJobNotificationDTO> notifications;
}
