package com.sspd.servicemgmt.core.ui.theme

import androidx.compose.ui.graphics.Color

// SSPD unified brand palette — Teal primary (matches Technician app)
val Primary      = Color(0xFF0F766E)
val PrimaryDark  = Color(0xFF0F2A3D)
val PrimaryLight = Color(0xFFE7F8F5)
val Accent       = Color(0xFF2DD4BF)
val Gold         = Color(0xFFD97706)
val Success      = Color(0xFF15803D)
val SuccessBg    = Color(0xFFECFDF3)
val Warning      = Color(0xFFB45309)
val WarningBg    = Color(0xFFFFF8E7)
val Danger       = Color(0xFFDC2626)
val DangerBg     = Color(0xFFFEF2F2)
val Violet       = Color(0xFF2563EB)
val VioletBg     = Color(0xFFEFF6FF)
val TextMain     = Color(0xFF172033)
val TextMuted    = Color(0xFF647184)
val BorderColor  = Color(0xFFDDE5EC)
val CardBg       = Color(0xFFFFFFFF)
val ScreenBg     = Color(0xFFF4F7FA)
val SurfaceSoft  = Color(0xFFF8FAFC)
val HeroTop      = Color(0xFF0F2A3D)
val HeroBottom   = Color(0xFF0F766E)
val OnPrimary    = Color(0xFFFFFFFF)
