ALTER TABLE delivery_pricing_policy
    ADD COLUMN opens_at TIME NOT NULL DEFAULT '09:00:00',
    ADD COLUMN closes_at TIME NOT NULL DEFAULT '18:00:00',
    ADD COLUMN delivery_days VARCHAR(80) NOT NULL DEFAULT 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY',
    ADD COLUMN weekday_hours JSON NULL,
    ADD COLUMN closed_dates JSON NULL,
    ADD COLUMN min_lead_days INT NOT NULL DEFAULT 1;
